/*
 * This source file was generated by the Gradle 'init' task
 */
    package org.example
        
class Complejo(private var real:Double=0.0,private var imaginario:Double=0.0){
    fun ponerValor(real:Double,imaginario:Double){ 
        this.real=real                             
        this.imaginario=imaginario
        }

        fun mostrar() {
            println(this.toString())
        }

        override fun toString():String{
            return "(${real},${imaginario})"
        }

        fun sumar(otro: Complejo): Complejo {
            return Complejo(
                real+otro.real,
                imaginario+otro.imaginario
            )   
        }

        fun restar(otro: Complejo): Complejo {
            return Complejo(
                real-otro.real,
                imaginario-otro.imaginario
            )   
        }

        fun multiplicar(otro: Complejo): Complejo {
            val nuevoReal = (this.real * otro.real) - (this.imaginario * otro.imaginario)
            val nuevoImaginario = (this.real * otro.imaginario) + (this.imaginario * otro.real)
            return Complejo(nuevoReal, nuevoImaginario)
        }

        fun dividir(otro: Complejo): Complejo {
            val denominador = (otro.real * otro.real) + (otro.imaginario * otro.imaginario)
            val nuevoReal = (this.real * otro.real + this.imaginario * otro.imaginario) / denominador
            val nuevoImaginario = (this.imaginario * otro.real - this.real * otro.imaginario) / denominador
            return Complejo(nuevoReal, nuevoImaginario)
        }
    }

    fun main() {
        var complejo:Complejo
        complejo=Complejo()
        complejo.ponerValor(3.0,4.0)
        println(complejo.mostrar())
        var c2:Complejo=Complejo(1.0,2.0)
        var c3:Complejo
        println("Suma")
        c3=complejo.sumar(c2)
        c3.mostrar()
        println("Resta")
        c2.ponerValor(2.0,4.0)
        c3=complejo.restar(c2)
        c3.mostrar()
        println("Multiplicación")
        c2.ponerValor(6.0,7.0)
        c3=complejo.multiplicar(c2)
        c3.mostrar()
        println("División")
        c2.ponerValor(3.0,6.0)
        c3=complejo.dividir(c2)
        c3.mostrar()
    }