/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo{
    private var real:Int=0
    private var imaginario:Int=0
    fun ponerValor(real:Int,imaginario:Int){ 
        this.real=real                             
        this.imaginario=imaginario
    }

    fun mostrar(): String {
        return "(${real},${imaginario})" 
    }

}
fun main() {
    var complejo:Complejo
    complejo=Complejo()
    complejo.ponerValor(3,4)
    println(complejo.mostrar())
    println("hola")
}